import { iRequestData } from './extructData';

export const getOpenWeatherMap = async (requestData: iRequestData) => {
    // const forecast = await fetch(
    //     `https://openweathermap.org/data/2.5/onecall?lat=55.7522&lon=37.6156&units=metric&appid=439d4b804bc8187953eb36d2a8c26a02`,
    // );
    // const res = await forecast.json();
    return {
        lat: 55.7522,
        lon: 37.6156,
        timezone: 'Europe/Moscow',
        timezone_offset: 10800,
        current: {
            dt: 1711516112,
            sunrise: 1711509165,
            sunset: 1711555002,
            temp: 0.84,
            feels_like: -2.56,
            pressure: 1017,
            humidity: 96,
            dew_point: 0.28,
            uvi: 0.25,
            clouds: 95,
            visibility: 10000,
            wind_speed: 3.08,
            wind_deg: 354,
            wind_gust: 5.19,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
        },
        minutely: [
            {
                dt: 1711516140,
                precipitation: 0,
            },
            {
                dt: 1711516200,
                precipitation: 0,
            },
            {
                dt: 1711516260,
                precipitation: 0,
            },
            {
                dt: 1711516320,
                precipitation: 0,
            },
            {
                dt: 1711516380,
                precipitation: 0,
            },
            {
                dt: 1711516440,
                precipitation: 0,
            },
            {
                dt: 1711516500,
                precipitation: 0,
            },
            {
                dt: 1711516560,
                precipitation: 0,
            },
            {
                dt: 1711516620,
                precipitation: 0,
            },
            {
                dt: 1711516680,
                precipitation: 0,
            },
            {
                dt: 1711516740,
                precipitation: 0,
            },
            {
                dt: 1711516800,
                precipitation: 0,
            },
            {
                dt: 1711516860,
                precipitation: 0,
            },
            {
                dt: 1711516920,
                precipitation: 0,
            },
            {
                dt: 1711516980,
                precipitation: 0,
            },
            {
                dt: 1711517040,
                precipitation: 0,
            },
            {
                dt: 1711517100,
                precipitation: 0,
            },
            {
                dt: 1711517160,
                precipitation: 0,
            },
            {
                dt: 1711517220,
                precipitation: 0,
            },
            {
                dt: 1711517280,
                precipitation: 0,
            },
            {
                dt: 1711517340,
                precipitation: 0,
            },
            {
                dt: 1711517400,
                precipitation: 0,
            },
            {
                dt: 1711517460,
                precipitation: 0,
            },
            {
                dt: 1711517520,
                precipitation: 0,
            },
            {
                dt: 1711517580,
                precipitation: 0,
            },
            {
                dt: 1711517640,
                precipitation: 0,
            },
            {
                dt: 1711517700,
                precipitation: 0,
            },
            {
                dt: 1711517760,
                precipitation: 0,
            },
            {
                dt: 1711517820,
                precipitation: 0,
            },
            {
                dt: 1711517880,
                precipitation: 0,
            },
            {
                dt: 1711517940,
                precipitation: 0,
            },
            {
                dt: 1711518000,
                precipitation: 0,
            },
            {
                dt: 1711518060,
                precipitation: 0,
            },
            {
                dt: 1711518120,
                precipitation: 0,
            },
            {
                dt: 1711518180,
                precipitation: 0,
            },
            {
                dt: 1711518240,
                precipitation: 0,
            },
            {
                dt: 1711518300,
                precipitation: 0,
            },
            {
                dt: 1711518360,
                precipitation: 0,
            },
            {
                dt: 1711518420,
                precipitation: 0,
            },
            {
                dt: 1711518480,
                precipitation: 0,
            },
            {
                dt: 1711518540,
                precipitation: 0,
            },
            {
                dt: 1711518600,
                precipitation: 0,
            },
            {
                dt: 1711518660,
                precipitation: 0,
            },
            {
                dt: 1711518720,
                precipitation: 0,
            },
            {
                dt: 1711518780,
                precipitation: 0,
            },
            {
                dt: 1711518840,
                precipitation: 0,
            },
            {
                dt: 1711518900,
                precipitation: 0,
            },
            {
                dt: 1711518960,
                precipitation: 0,
            },
            {
                dt: 1711519020,
                precipitation: 0,
            },
            {
                dt: 1711519080,
                precipitation: 0,
            },
            {
                dt: 1711519140,
                precipitation: 0,
            },
            {
                dt: 1711519200,
                precipitation: 0,
            },
            {
                dt: 1711519260,
                precipitation: 0,
            },
            {
                dt: 1711519320,
                precipitation: 0,
            },
            {
                dt: 1711519380,
                precipitation: 0,
            },
            {
                dt: 1711519440,
                precipitation: 0,
            },
            {
                dt: 1711519500,
                precipitation: 0,
            },
            {
                dt: 1711519560,
                precipitation: 0,
            },
            {
                dt: 1711519620,
                precipitation: 0,
            },
            {
                dt: 1711519680,
                precipitation: 0,
            },
        ],
        hourly: [
            {
                dt: 1711515600,
                temp: 0.84,
                feels_like: -2.56,
                pressure: 1017,
                humidity: 96,
                dew_point: 0.28,
                uvi: 0.25,
                clouds: 95,
                visibility: 10000,
                wind_speed: 3.08,
                wind_deg: 354,
                wind_gust: 5.19,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711519200,
                temp: 0.6,
                feels_like: -2.9,
                pressure: 1017,
                humidity: 95,
                dew_point: -0.09,
                uvi: 0.59,
                clouds: 95,
                visibility: 10000,
                wind_speed: 3.14,
                wind_deg: 354,
                wind_gust: 4.9,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711522800,
                temp: 0.5,
                feels_like: -2.67,
                pressure: 1017,
                humidity: 96,
                dew_point: -0.05,
                uvi: 1.07,
                clouds: 97,
                visibility: 10000,
                wind_speed: 2.75,
                wind_deg: 351,
                wind_gust: 4.6,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711526400,
                temp: 0.56,
                feels_like: -2.49,
                pressure: 1017,
                humidity: 97,
                dew_point: 0.14,
                uvi: 1.68,
                clouds: 98,
                visibility: 10000,
                wind_speed: 2.63,
                wind_deg: 345,
                wind_gust: 4.11,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711530000,
                temp: 0.81,
                feels_like: -2.12,
                pressure: 1017,
                humidity: 97,
                dew_point: 0.39,
                uvi: 2.26,
                clouds: 99,
                visibility: 10000,
                wind_speed: 2.56,
                wind_deg: 340,
                wind_gust: 3.93,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711533600,
                temp: 1.32,
                feels_like: -1.29,
                pressure: 1017,
                humidity: 95,
                dew_point: 0.6,
                uvi: 2.33,
                clouds: 100,
                visibility: 10000,
                wind_speed: 2.33,
                wind_deg: 344,
                wind_gust: 3.59,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711537200,
                temp: 1.79,
                feels_like: -0.2,
                pressure: 1017,
                humidity: 93,
                dew_point: 0.84,
                uvi: 1.95,
                clouds: 100,
                visibility: 10000,
                wind_speed: 1.86,
                wind_deg: 351,
                wind_gust: 2.96,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711540800,
                temp: 2.74,
                feels_like: 2.74,
                pressure: 1017,
                humidity: 92,
                dew_point: 1.55,
                uvi: 1.41,
                clouds: 97,
                visibility: 53,
                wind_speed: 0.99,
                wind_deg: 18,
                wind_gust: 2.17,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711544400,
                temp: 2.08,
                feels_like: 2.08,
                pressure: 1018,
                humidity: 92,
                dew_point: 0.93,
                uvi: 0.83,
                clouds: 79,
                wind_speed: 0.27,
                wind_deg: 63,
                wind_gust: 0.93,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711548000,
                temp: 1.45,
                feels_like: 1.45,
                pressure: 1018,
                humidity: 95,
                dew_point: 0.76,
                uvi: 0.36,
                clouds: 79,
                wind_speed: 0.41,
                wind_deg: 155,
                wind_gust: 0.05,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711551600,
                temp: 0.72,
                feels_like: 0.72,
                pressure: 1018,
                humidity: 95,
                dew_point: -0.01,
                uvi: 0.11,
                clouds: 79,
                wind_speed: 0.27,
                wind_deg: 186,
                wind_gust: 0.36,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711555200,
                temp: -0.09,
                feels_like: -0.09,
                pressure: 1018,
                humidity: 96,
                dew_point: -0.74,
                uvi: 0,
                clouds: 80,
                wind_speed: 0.25,
                wind_deg: 268,
                wind_gust: 0.35,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711558800,
                temp: -0.45,
                feels_like: -0.45,
                pressure: 1019,
                humidity: 96,
                dew_point: -1.15,
                uvi: 0,
                clouds: 82,
                wind_speed: 0.15,
                wind_deg: 233,
                wind_gust: 0.33,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711562400,
                temp: -0.58,
                feels_like: -0.58,
                pressure: 1019,
                humidity: 96,
                dew_point: -1.15,
                uvi: 0,
                clouds: 83,
                wind_speed: 0.44,
                wind_deg: 174,
                wind_gust: 0.48,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711566000,
                temp: -0.57,
                feels_like: -0.57,
                pressure: 1019,
                humidity: 97,
                dew_point: -1.16,
                uvi: 0,
                clouds: 92,
                visibility: 10000,
                wind_speed: 0.84,
                wind_deg: 205,
                wind_gust: 0.92,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711569600,
                temp: -0.68,
                feels_like: -0.68,
                pressure: 1019,
                humidity: 95,
                dew_point: -1.35,
                uvi: 0,
                clouds: 92,
                visibility: 10000,
                wind_speed: 1.18,
                wind_deg: 210,
                wind_gust: 1.26,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711573200,
                temp: -1.06,
                feels_like: -1.06,
                pressure: 1019,
                humidity: 94,
                dew_point: -1.91,
                uvi: 0,
                clouds: 90,
                visibility: 10000,
                wind_speed: 1.21,
                wind_deg: 216,
                wind_gust: 1.25,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711576800,
                temp: -1.43,
                feels_like: -3.12,
                pressure: 1019,
                humidity: 94,
                dew_point: -2.37,
                uvi: 0,
                clouds: 88,
                visibility: 10000,
                wind_speed: 1.35,
                wind_deg: 207,
                wind_gust: 1.17,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711580400,
                temp: -1.15,
                feels_like: -3.08,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.16,
                uvi: 0,
                clouds: 91,
                visibility: 10000,
                wind_speed: 1.51,
                wind_deg: 217,
                wind_gust: 1.78,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711584000,
                temp: -1.33,
                feels_like: -3.2,
                pressure: 1020,
                humidity: 94,
                dew_point: -2.3,
                uvi: 0,
                clouds: 92,
                visibility: 10000,
                wind_speed: 1.46,
                wind_deg: 209,
                wind_gust: 1.8,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711587600,
                temp: -1.49,
                feels_like: -3.4,
                pressure: 1019,
                humidity: 93,
                dew_point: -2.46,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 1.47,
                wind_deg: 207,
                wind_gust: 1.73,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711591200,
                temp: -1.62,
                feels_like: -3.53,
                pressure: 1019,
                humidity: 93,
                dew_point: -2.56,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 1.46,
                wind_deg: 197,
                wind_gust: 2.1,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711594800,
                temp: -1.44,
                feels_like: -3.73,
                pressure: 1019,
                humidity: 94,
                dew_point: -2.45,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 1.71,
                wind_deg: 194,
                wind_gust: 2.18,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711598400,
                temp: -1.07,
                feels_like: -3.24,
                pressure: 1019,
                humidity: 93,
                dew_point: -2.11,
                uvi: 0.12,
                clouds: 99,
                visibility: 10000,
                wind_speed: 1.67,
                wind_deg: 186,
                wind_gust: 3.32,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711602000,
                temp: 0.29,
                feels_like: -2.07,
                pressure: 1019,
                humidity: 90,
                dew_point: -1.11,
                uvi: 0.45,
                clouds: 98,
                visibility: 10000,
                wind_speed: 1.96,
                wind_deg: 181,
                wind_gust: 5.34,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711605600,
                temp: 1.13,
                feels_like: -1.67,
                pressure: 1020,
                humidity: 90,
                dew_point: -0.34,
                uvi: 0.97,
                clouds: 96,
                visibility: 10000,
                wind_speed: 2.49,
                wind_deg: 177,
                wind_gust: 5.72,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711609200,
                temp: 1.82,
                feels_like: -1.28,
                pressure: 1019,
                humidity: 88,
                dew_point: -0.02,
                uvi: 1.56,
                clouds: 94,
                visibility: 10000,
                wind_speed: 2.96,
                wind_deg: 171,
                wind_gust: 5.89,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711612800,
                temp: 2.69,
                feels_like: -0.32,
                pressure: 1019,
                humidity: 85,
                dew_point: 0.23,
                uvi: 2.08,
                clouds: 97,
                visibility: 10000,
                wind_speed: 3.07,
                wind_deg: 169,
                wind_gust: 6.11,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711616400,
                temp: 3.6,
                feels_like: 0.63,
                pressure: 1018,
                humidity: 81,
                dew_point: 0.58,
                uvi: 2.35,
                clouds: 98,
                visibility: 10000,
                wind_speed: 3.26,
                wind_deg: 167,
                wind_gust: 6.4,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711620000,
                temp: 4.39,
                feels_like: 1.52,
                pressure: 1018,
                humidity: 77,
                dew_point: 0.68,
                uvi: 2.45,
                clouds: 99,
                visibility: 10000,
                wind_speed: 3.35,
                wind_deg: 167,
                wind_gust: 6.93,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711623600,
                temp: 4.81,
                feels_like: 1.82,
                pressure: 1017,
                humidity: 73,
                dew_point: 0.39,
                uvi: 2.22,
                clouds: 99,
                visibility: 10000,
                wind_speed: 3.68,
                wind_deg: 169,
                wind_gust: 7.5,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711627200,
                temp: 5.08,
                feels_like: 2.03,
                pressure: 1016,
                humidity: 73,
                dew_point: 0.45,
                uvi: 1.63,
                clouds: 99,
                visibility: 10000,
                wind_speed: 3.87,
                wind_deg: 170,
                wind_gust: 7.87,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711630800,
                temp: 4.86,
                feels_like: 1.88,
                pressure: 1016,
                humidity: 75,
                dew_point: 0.72,
                uvi: 0.97,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.67,
                wind_deg: 167,
                wind_gust: 7.99,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711634400,
                temp: 4.35,
                feels_like: 1.48,
                pressure: 1015,
                humidity: 78,
                dew_point: 0.82,
                uvi: 0.44,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.34,
                wind_deg: 160,
                wind_gust: 8.41,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711638000,
                temp: 3.47,
                feels_like: 0.6,
                pressure: 1015,
                humidity: 82,
                dew_point: 0.52,
                uvi: 0.13,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.09,
                wind_deg: 159,
                wind_gust: 8.53,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711641600,
                temp: 2.53,
                feels_like: -0.46,
                pressure: 1015,
                humidity: 85,
                dew_point: 0.27,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3,
                wind_deg: 153,
                wind_gust: 8.94,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711645200,
                temp: 2.09,
                feels_like: -1.12,
                pressure: 1015,
                humidity: 87,
                dew_point: 0.18,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.16,
                wind_deg: 150,
                wind_gust: 10.37,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711648800,
                temp: 2.11,
                feels_like: -1.39,
                pressure: 1014,
                humidity: 87,
                dew_point: -0.01,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.55,
                wind_deg: 153,
                wind_gust: 11.71,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711652400,
                temp: 1.88,
                feels_like: -1.59,
                pressure: 1014,
                humidity: 88,
                dew_point: 0.01,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.45,
                wind_deg: 153,
                wind_gust: 12.52,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711656000,
                temp: 1.83,
                feels_like: -1.59,
                pressure: 1013,
                humidity: 89,
                dew_point: 0.11,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.36,
                wind_deg: 151,
                wind_gust: 12.42,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711659600,
                temp: 1.85,
                feels_like: -1.39,
                pressure: 1013,
                humidity: 89,
                dew_point: 0.23,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.14,
                wind_deg: 150,
                wind_gust: 11.77,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711663200,
                temp: 2.13,
                feels_like: -1.11,
                pressure: 1012,
                humidity: 91,
                dew_point: 0.68,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.21,
                wind_deg: 153,
                wind_gust: 11.55,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711666800,
                temp: 2.47,
                feels_like: -1,
                pressure: 1011,
                humidity: 92,
                dew_point: 1.26,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.63,
                wind_deg: 148,
                wind_gust: 11.55,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711670400,
                temp: 2.79,
                feels_like: -0.79,
                pressure: 1010,
                humidity: 91,
                dew_point: 1.43,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.89,
                wind_deg: 151,
                wind_gust: 11.83,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711674000,
                temp: 2.89,
                feels_like: -0.46,
                pressure: 1010,
                humidity: 92,
                dew_point: 1.6,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.59,
                wind_deg: 153,
                wind_gust: 12.98,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711677600,
                temp: 3.14,
                feels_like: -0.2,
                pressure: 1009,
                humidity: 91,
                dew_point: 1.79,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.65,
                wind_deg: 154,
                wind_gust: 12.6,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711681200,
                temp: 3.15,
                feels_like: -0.17,
                pressure: 1009,
                humidity: 88,
                dew_point: 1.25,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.62,
                wind_deg: 155,
                wind_gust: 10.54,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711684800,
                temp: 2.95,
                feels_like: -0.34,
                pressure: 1008,
                humidity: 87,
                dew_point: 0.96,
                uvi: 0.06,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.51,
                wind_deg: 149,
                wind_gust: 10.34,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
        ],
        daily: [
            {
                dt: 1711530000,
                sunrise: 1711509165,
                sunset: 1711555002,
                moonrise: 1711565220,
                moonset: 1711510680,
                moon_phase: 0.56,
                temp: {
                    day: 0.81,
                    min: -4.22,
                    max: 2.74,
                    night: -0.68,
                    eve: 0.72,
                    morn: -0.54,
                },
                feels_like: {
                    day: -2.12,
                    night: -0.68,
                    eve: 0.72,
                    morn: -4.02,
                },
                pressure: 1017,
                humidity: 97,
                dew_point: 0.39,
                wind_speed: 3.14,
                wind_deg: 354,
                wind_gust: 5.42,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 99,
                pop: 0,
                uvi: 2.33,
            },
            {
                dt: 1711616400,
                sunrise: 1711595407,
                sunset: 1711641522,
                moonrise: 1711656600,
                moonset: 1711597500,
                moon_phase: 0.59,
                temp: {
                    day: 3.6,
                    min: -1.62,
                    max: 5.08,
                    night: 1.83,
                    eve: 3.47,
                    morn: -1.44,
                },
                feels_like: {
                    day: 0.63,
                    night: -1.59,
                    eve: 0.6,
                    morn: -3.73,
                },
                pressure: 1018,
                humidity: 81,
                dew_point: 0.58,
                wind_speed: 3.87,
                wind_deg: 170,
                wind_gust: 12.52,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 98,
                pop: 0,
                uvi: 2.45,
            },
            {
                dt: 1711702800,
                sunrise: 1711681650,
                sunset: 1711728042,
                moonrise: 0,
                moonset: 1711684500,
                moon_phase: 0.63,
                temp: {
                    day: 4.53,
                    min: 1.85,
                    max: 5.86,
                    night: 3.65,
                    eve: 5.23,
                    morn: 3.15,
                },
                feels_like: {
                    day: 1.47,
                    night: 1.47,
                    eve: 3.17,
                    morn: -0.17,
                },
                pressure: 1007,
                humidity: 91,
                dew_point: 3.19,
                wind_speed: 3.89,
                wind_deg: 151,
                wind_gust: 12.98,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                clouds: 100,
                pop: 0.97,
                rain: 0.44,
                uvi: 1.37,
            },
            {
                dt: 1711789200,
                sunrise: 1711767892,
                sunset: 1711814562,
                moonrise: 1711748100,
                moonset: 1711771800,
                moon_phase: 0.66,
                temp: {
                    day: 9.17,
                    min: 3,
                    max: 11.12,
                    night: 7.41,
                    eve: 9.41,
                    morn: 3,
                },
                feels_like: {
                    day: 6.92,
                    night: 5.21,
                    eve: 7.85,
                    morn: 0.49,
                },
                pressure: 1015,
                humidity: 64,
                dew_point: 2.61,
                wind_speed: 4.22,
                wind_deg: 260,
                wind_gust: 9.95,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                clouds: 51,
                pop: 0,
                uvi: 2.28,
            },
            {
                dt: 1711875600,
                sunrise: 1711854135,
                sunset: 1711901082,
                moonrise: 1711839540,
                moonset: 1711859700,
                moon_phase: 0.69,
                temp: {
                    day: 13.76,
                    min: 6.83,
                    max: 16.26,
                    night: 10.95,
                    eve: 14.05,
                    morn: 6.83,
                },
                feels_like: {
                    day: 12.76,
                    night: 10.24,
                    eve: 13.18,
                    morn: 4.28,
                },
                pressure: 1014,
                humidity: 60,
                dew_point: 6.02,
                wind_speed: 4.65,
                wind_deg: 234,
                wind_gust: 12.7,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                clouds: 83,
                pop: 0,
                uvi: 2.99,
            },
            {
                dt: 1711962000,
                sunrise: 1711940378,
                sunset: 1711987602,
                moonrise: 1711930380,
                moonset: 1711948680,
                moon_phase: 0.72,
                temp: {
                    day: 14.17,
                    min: 7.16,
                    max: 15.8,
                    night: 13.62,
                    eve: 15.04,
                    morn: 7.16,
                },
                feels_like: {
                    day: 13.31,
                    night: 12.84,
                    eve: 14.17,
                    morn: 5.06,
                },
                pressure: 1010,
                humidity: 64,
                dew_point: 7.41,
                wind_speed: 6.17,
                wind_deg: 205,
                wind_gust: 15.42,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 100,
                pop: 0,
                uvi: 3,
            },
            {
                dt: 1712048400,
                sunrise: 1712026621,
                sunset: 1712074122,
                moonrise: 1712020080,
                moonset: 1712039100,
                moon_phase: 0.75,
                temp: {
                    day: 15.38,
                    min: 10.04,
                    max: 17.25,
                    night: 13.77,
                    eve: 15.78,
                    morn: 10.04,
                },
                feels_like: {
                    day: 14.41,
                    night: 12.85,
                    eve: 14.72,
                    morn: 9.24,
                },
                pressure: 1004,
                humidity: 55,
                dew_point: 6.48,
                wind_speed: 6.22,
                wind_deg: 184,
                wind_gust: 14.87,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 100,
                pop: 0,
                uvi: 3,
            },
            {
                dt: 1712134800,
                sunrise: 1712112865,
                sunset: 1712160643,
                moonrise: 1712108580,
                moonset: 1712130780,
                moon_phase: 0.79,
                temp: {
                    day: 14.59,
                    min: 5.47,
                    max: 14.59,
                    night: 5.47,
                    eve: 10.01,
                    morn: 9.28,
                },
                feels_like: {
                    day: 13.57,
                    night: 1.12,
                    eve: 9.02,
                    morn: 6.6,
                },
                pressure: 994,
                humidity: 56,
                dew_point: 5.88,
                wind_speed: 7.54,
                wind_deg: 233,
                wind_gust: 14.29,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                clouds: 70,
                pop: 1,
                rain: 1.29,
                uvi: 3,
            },
        ],
        alerts: [
            {
                sender_name: 'web@mecom.ru',
                event: 'Other dangers',
                start: 1711508400,
                end: 1711612800,
                description: '',
                tags: ['Other dangers'],
            },
            {
                sender_name: 'web@mecom.ru',
                event: 'Прочие опасности',
                start: 1711508400,
                end: 1711612800,
                description: 'В ночные и утренние часы на дорогах местами гололедица.',
                tags: ['Other dangers'],
            },
        ],
    };
};
