import { iRequestData } from './extructData';

export const getOpenWeatherMap = async (requestData: iRequestData) => {
    // const forecast = await fetch(
    //     `https://openweathermap.org/data/2.5/onecall?lat=55.7522&lon=37.6156&units=metric&appid=439d4b804bc8187953eb36d2a8c26a02`,
    // );
    // const res = await forecast.json();
    return {
        lat: 55.7522,
        lon: 37.6156,
        timezone: 'Europe/Moscow',
        timezone_offset: 10800,
        current: {
            dt: 1711483767,
            sunrise: 1711422923,
            sunset: 1711468482,
            temp: 3.22,
            feels_like: 1.05,
            pressure: 1014,
            humidity: 97,
            dew_point: 2.79,
            uvi: 0,
            clouds: 99,
            visibility: 10000,
            wind_speed: 2.23,
            wind_deg: 3,
            wind_gust: 4.58,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
        },
        minutely: [
            {
                dt: 1711483800,
                precipitation: 0,
            },
            {
                dt: 1711483860,
                precipitation: 0,
            },
            {
                dt: 1711483920,
                precipitation: 0,
            },
            {
                dt: 1711483980,
                precipitation: 0,
            },
            {
                dt: 1711484040,
                precipitation: 0,
            },
            {
                dt: 1711484100,
                precipitation: 0,
            },
            {
                dt: 1711484160,
                precipitation: 0,
            },
            {
                dt: 1711484220,
                precipitation: 0,
            },
            {
                dt: 1711484280,
                precipitation: 0,
            },
            {
                dt: 1711484340,
                precipitation: 0,
            },
            {
                dt: 1711484400,
                precipitation: 0,
            },
            {
                dt: 1711484460,
                precipitation: 0,
            },
            {
                dt: 1711484520,
                precipitation: 0,
            },
            {
                dt: 1711484580,
                precipitation: 0,
            },
            {
                dt: 1711484640,
                precipitation: 0,
            },
            {
                dt: 1711484700,
                precipitation: 0,
            },
            {
                dt: 1711484760,
                precipitation: 0,
            },
            {
                dt: 1711484820,
                precipitation: 0,
            },
            {
                dt: 1711484880,
                precipitation: 0,
            },
            {
                dt: 1711484940,
                precipitation: 0,
            },
            {
                dt: 1711485000,
                precipitation: 0,
            },
            {
                dt: 1711485060,
                precipitation: 0,
            },
            {
                dt: 1711485120,
                precipitation: 0,
            },
            {
                dt: 1711485180,
                precipitation: 0,
            },
            {
                dt: 1711485240,
                precipitation: 0,
            },
            {
                dt: 1711485300,
                precipitation: 0,
            },
            {
                dt: 1711485360,
                precipitation: 0,
            },
            {
                dt: 1711485420,
                precipitation: 0,
            },
            {
                dt: 1711485480,
                precipitation: 0,
            },
            {
                dt: 1711485540,
                precipitation: 0,
            },
            {
                dt: 1711485600,
                precipitation: 0,
            },
            {
                dt: 1711485660,
                precipitation: 0,
            },
            {
                dt: 1711485720,
                precipitation: 0,
            },
            {
                dt: 1711485780,
                precipitation: 0,
            },
            {
                dt: 1711485840,
                precipitation: 0,
            },
            {
                dt: 1711485900,
                precipitation: 0,
            },
            {
                dt: 1711485960,
                precipitation: 0,
            },
            {
                dt: 1711486020,
                precipitation: 0,
            },
            {
                dt: 1711486080,
                precipitation: 0,
            },
            {
                dt: 1711486140,
                precipitation: 0,
            },
            {
                dt: 1711486200,
                precipitation: 0,
            },
            {
                dt: 1711486260,
                precipitation: 0,
            },
            {
                dt: 1711486320,
                precipitation: 0,
            },
            {
                dt: 1711486380,
                precipitation: 0,
            },
            {
                dt: 1711486440,
                precipitation: 0,
            },
            {
                dt: 1711486500,
                precipitation: 0,
            },
            {
                dt: 1711486560,
                precipitation: 0,
            },
            {
                dt: 1711486620,
                precipitation: 0,
            },
            {
                dt: 1711486680,
                precipitation: 0,
            },
            {
                dt: 1711486740,
                precipitation: 0,
            },
            {
                dt: 1711486800,
                precipitation: 0,
            },
            {
                dt: 1711486860,
                precipitation: 0,
            },
            {
                dt: 1711486920,
                precipitation: 0,
            },
            {
                dt: 1711486980,
                precipitation: 0,
            },
            {
                dt: 1711487040,
                precipitation: 0,
            },
            {
                dt: 1711487100,
                precipitation: 0,
            },
            {
                dt: 1711487160,
                precipitation: 0,
            },
            {
                dt: 1711487220,
                precipitation: 0,
            },
            {
                dt: 1711487280,
                precipitation: 0,
            },
            {
                dt: 1711487340,
                precipitation: 0,
            },
        ],
        hourly: [
            {
                dt: 1711483200,
                temp: 3.22,
                feels_like: 1.05,
                pressure: 1014,
                humidity: 97,
                dew_point: 2.79,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 2.23,
                wind_deg: 3,
                wind_gust: 4.58,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711486800,
                temp: 2.22,
                feels_like: 0.03,
                pressure: 1014,
                humidity: 98,
                dew_point: 1.94,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 2.09,
                wind_deg: 1,
                wind_gust: 4.5,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711490400,
                temp: 0.86,
                feels_like: -1.42,
                pressure: 1014,
                humidity: 98,
                dew_point: 0.58,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 1.97,
                wind_deg: 2,
                wind_gust: 4.01,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711494000,
                temp: -0.96,
                feels_like: -3.4,
                pressure: 1015,
                humidity: 99,
                dew_point: -1.08,
                uvi: 0,
                clouds: 95,
                visibility: 10000,
                wind_speed: 1.87,
                wind_deg: 357,
                wind_gust: 3.67,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711497600,
                temp: -2.05,
                feels_like: -5.06,
                pressure: 1015,
                humidity: 99,
                dew_point: -2.17,
                uvi: 0,
                clouds: 93,
                visibility: 653,
                wind_speed: 2.17,
                wind_deg: 360,
                wind_gust: 4.57,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711501200,
                temp: -2.84,
                feels_like: -6.54,
                pressure: 1016,
                humidity: 99,
                dew_point: -3.17,
                uvi: 0,
                clouds: 100,
                visibility: 572,
                wind_speed: 2.64,
                wind_deg: 2,
                wind_gust: 5.6,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711504800,
                temp: -2.84,
                feels_like: -6.5,
                pressure: 1016,
                humidity: 98,
                dew_point: -3.19,
                uvi: 0,
                clouds: 100,
                wind_speed: 2.6,
                wind_deg: 2,
                wind_gust: 4.86,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711508400,
                temp: -2.84,
                feels_like: -6.66,
                pressure: 1016,
                humidity: 98,
                dew_point: -3.2,
                uvi: 0,
                clouds: 100,
                visibility: 337,
                wind_speed: 2.75,
                wind_deg: 352,
                wind_gust: 5.09,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711512000,
                temp: -2.19,
                feels_like: -6,
                pressure: 1017,
                humidity: 98,
                dew_point: -2.58,
                uvi: 0.07,
                clouds: 100,
                visibility: 293,
                wind_speed: 2.87,
                wind_deg: 351,
                wind_gust: 5.3,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711515600,
                temp: -1.26,
                feels_like: -5,
                pressure: 1017,
                humidity: 96,
                dew_point: -1.87,
                uvi: 0.25,
                clouds: 100,
                visibility: 10000,
                wind_speed: 2.99,
                wind_deg: 352,
                wind_gust: 5.01,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711519200,
                temp: -0.63,
                feels_like: -4.18,
                pressure: 1017,
                humidity: 95,
                dew_point: -1.23,
                uvi: 0.59,
                clouds: 100,
                visibility: 10000,
                wind_speed: 2.92,
                wind_deg: 356,
                wind_gust: 4.76,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711522800,
                temp: -0.07,
                feels_like: -3.43,
                pressure: 1017,
                humidity: 97,
                dew_point: -0.58,
                uvi: 1.07,
                clouds: 100,
                visibility: 10000,
                wind_speed: 2.83,
                wind_deg: 352,
                wind_gust: 4.5,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711526400,
                temp: 0.35,
                feels_like: -2.82,
                pressure: 1017,
                humidity: 97,
                dew_point: -0.13,
                uvi: 1.68,
                clouds: 100,
                visibility: 10000,
                wind_speed: 2.72,
                wind_deg: 344,
                wind_gust: 4.14,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711530000,
                temp: 0.81,
                feels_like: -2.02,
                pressure: 1017,
                humidity: 97,
                dew_point: 0.19,
                uvi: 2.26,
                clouds: 99,
                visibility: 10000,
                wind_speed: 2.46,
                wind_deg: 345,
                wind_gust: 3.68,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711533600,
                temp: 1.29,
                feels_like: -1.14,
                pressure: 1017,
                humidity: 95,
                dew_point: 0.55,
                uvi: 2.33,
                clouds: 100,
                visibility: 10000,
                wind_speed: 2.16,
                wind_deg: 348,
                wind_gust: 3.3,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711537200,
                temp: 1.71,
                feels_like: -0.23,
                pressure: 1018,
                humidity: 93,
                dew_point: 0.76,
                uvi: 1.95,
                clouds: 100,
                visibility: 10000,
                wind_speed: 1.81,
                wind_deg: 358,
                wind_gust: 2.56,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711540800,
                temp: 2.68,
                feels_like: 2.68,
                pressure: 1018,
                humidity: 93,
                dew_point: 1.55,
                uvi: 1.41,
                clouds: 100,
                visibility: 53,
                wind_speed: 0.96,
                wind_deg: 7,
                wind_gust: 1.87,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711544400,
                temp: 1.92,
                feels_like: 1.92,
                pressure: 1018,
                humidity: 93,
                dew_point: 0.88,
                uvi: 0.83,
                clouds: 86,
                wind_speed: 0.4,
                wind_deg: 21,
                wind_gust: 1.33,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711548000,
                temp: 1.35,
                feels_like: 1.35,
                pressure: 1018,
                humidity: 95,
                dew_point: 0.68,
                uvi: 0.36,
                clouds: 83,
                wind_speed: 0.3,
                wind_deg: 138,
                wind_gust: 0.28,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711551600,
                temp: 0.74,
                feels_like: 0.74,
                pressure: 1018,
                humidity: 96,
                dew_point: 0.09,
                uvi: 0.11,
                clouds: 83,
                wind_speed: 0.36,
                wind_deg: 199,
                wind_gust: 0.48,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711555200,
                temp: -0.07,
                feels_like: -0.07,
                pressure: 1019,
                humidity: 96,
                dew_point: -0.58,
                uvi: 0,
                clouds: 83,
                wind_speed: 0.33,
                wind_deg: 247,
                wind_gust: 0.46,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711558800,
                temp: -0.55,
                feels_like: -0.55,
                pressure: 1019,
                humidity: 96,
                dew_point: -1.11,
                uvi: 0,
                clouds: 84,
                wind_speed: 0.38,
                wind_deg: 235,
                wind_gust: 0.45,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711562400,
                temp: -0.71,
                feels_like: -0.71,
                pressure: 1019,
                humidity: 96,
                dew_point: -1.27,
                uvi: 0,
                clouds: 85,
                wind_speed: 0.66,
                wind_deg: 211,
                wind_gust: 0.73,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711566000,
                temp: -0.83,
                feels_like: -0.83,
                pressure: 1019,
                humidity: 96,
                dew_point: -1.51,
                uvi: 0,
                clouds: 96,
                visibility: 4941,
                wind_speed: 0.96,
                wind_deg: 222,
                wind_gust: 1.02,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711569600,
                temp: -1.17,
                feels_like: -1.17,
                pressure: 1019,
                humidity: 95,
                dew_point: -1.98,
                uvi: 0,
                clouds: 92,
                visibility: 10000,
                wind_speed: 1.12,
                wind_deg: 210,
                wind_gust: 1.04,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711573200,
                temp: -1.51,
                feels_like: -1.51,
                pressure: 1019,
                humidity: 94,
                dew_point: -2.43,
                uvi: 0,
                clouds: 77,
                visibility: 10000,
                wind_speed: 1.18,
                wind_deg: 209,
                wind_gust: 1.17,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711576800,
                temp: -1.53,
                feels_like: -3.4,
                pressure: 1020,
                humidity: 94,
                dew_point: -2.52,
                uvi: 0,
                clouds: 68,
                visibility: 10000,
                wind_speed: 1.44,
                wind_deg: 211,
                wind_gust: 1.36,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711580400,
                temp: -1.73,
                feels_like: -3.83,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.72,
                uvi: 0,
                clouds: 61,
                visibility: 10000,
                wind_speed: 1.56,
                wind_deg: 217,
                wind_gust: 1.76,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711584000,
                temp: -1.63,
                feels_like: -3.58,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.59,
                uvi: 0,
                clouds: 68,
                visibility: 10000,
                wind_speed: 1.48,
                wind_deg: 215,
                wind_gust: 1.83,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711587600,
                temp: -1.64,
                feels_like: -3.59,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.63,
                uvi: 0,
                clouds: 98,
                visibility: 10000,
                wind_speed: 1.48,
                wind_deg: 215,
                wind_gust: 2.11,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711591200,
                temp: -1.68,
                feels_like: -3.79,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.72,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 1.57,
                wind_deg: 208,
                wind_gust: 2.18,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711594800,
                temp: -1.85,
                feels_like: -3.98,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.87,
                uvi: 0,
                clouds: 95,
                visibility: 10000,
                wind_speed: 1.57,
                wind_deg: 196,
                wind_gust: 2.16,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711598400,
                temp: -1.37,
                feels_like: -3.82,
                pressure: 1020,
                humidity: 93,
                dew_point: -2.53,
                uvi: 0.12,
                clouds: 95,
                visibility: 10000,
                wind_speed: 1.83,
                wind_deg: 194,
                wind_gust: 3.47,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711602000,
                temp: 0.2,
                feels_like: -2.28,
                pressure: 1020,
                humidity: 89,
                dew_point: -1.3,
                uvi: 0.45,
                clouds: 94,
                visibility: 10000,
                wind_speed: 2.05,
                wind_deg: 187,
                wind_gust: 5.62,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711605600,
                temp: 1.02,
                feels_like: -1.66,
                pressure: 1020,
                humidity: 89,
                dew_point: -0.72,
                uvi: 0.97,
                clouds: 95,
                visibility: 10000,
                wind_speed: 2.35,
                wind_deg: 179,
                wind_gust: 5.78,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711609200,
                temp: 1.77,
                feels_like: -1.21,
                pressure: 1020,
                humidity: 87,
                dew_point: -0.24,
                uvi: 1.56,
                clouds: 98,
                visibility: 10000,
                wind_speed: 2.81,
                wind_deg: 177,
                wind_gust: 5.83,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711612800,
                temp: 2.56,
                feels_like: -0.36,
                pressure: 1019,
                humidity: 85,
                dew_point: 0.2,
                uvi: 2.08,
                clouds: 95,
                visibility: 10000,
                wind_speed: 2.92,
                wind_deg: 170,
                wind_gust: 5.89,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711616400,
                temp: 3.49,
                feels_like: 0.59,
                pressure: 1019,
                humidity: 81,
                dew_point: 0.41,
                uvi: 2.35,
                clouds: 96,
                visibility: 10000,
                wind_speed: 3.13,
                wind_deg: 170,
                wind_gust: 6.27,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711620000,
                temp: 4.33,
                feels_like: 1.42,
                pressure: 1018,
                humidity: 76,
                dew_point: 0.42,
                uvi: 2.45,
                clouds: 97,
                visibility: 10000,
                wind_speed: 3.39,
                wind_deg: 171,
                wind_gust: 7.01,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711623600,
                temp: 4.97,
                feels_like: 2.01,
                pressure: 1017,
                humidity: 73,
                dew_point: 0.44,
                uvi: 2.22,
                clouds: 95,
                visibility: 10000,
                wind_speed: 3.69,
                wind_deg: 173,
                wind_gust: 7.4,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711627200,
                temp: 5.29,
                feels_like: 2.26,
                pressure: 1017,
                humidity: 72,
                dew_point: 0.46,
                uvi: 1.63,
                clouds: 86,
                visibility: 10000,
                wind_speed: 3.93,
                wind_deg: 174,
                wind_gust: 7.83,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711630800,
                temp: 5.41,
                feels_like: 2.41,
                pressure: 1016,
                humidity: 73,
                dew_point: 0.87,
                uvi: 0.97,
                clouds: 20,
                visibility: 10000,
                wind_speed: 3.92,
                wind_deg: 172,
                wind_gust: 8.1,
                weather: [
                    {
                        id: 801,
                        main: 'Clouds',
                        description: 'few clouds',
                        icon: '02d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711634400,
                temp: 4.83,
                feels_like: 1.87,
                pressure: 1016,
                humidity: 77,
                dew_point: 1.11,
                uvi: 0.44,
                clouds: 27,
                visibility: 10000,
                wind_speed: 3.64,
                wind_deg: 168,
                wind_gust: 8.43,
                weather: [
                    {
                        id: 802,
                        main: 'Clouds',
                        description: 'scattered clouds',
                        icon: '03d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711638000,
                temp: 3.83,
                feels_like: 0.91,
                pressure: 1015,
                humidity: 81,
                dew_point: 0.9,
                uvi: 0.13,
                clouds: 49,
                visibility: 10000,
                wind_speed: 3.26,
                wind_deg: 164,
                wind_gust: 8.69,
                weather: [
                    {
                        id: 802,
                        main: 'Clouds',
                        description: 'scattered clouds',
                        icon: '03d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711641600,
                temp: 2.95,
                feels_like: 0,
                pressure: 1015,
                humidity: 85,
                dew_point: 0.52,
                uvi: 0,
                clouds: 62,
                visibility: 10000,
                wind_speed: 3.05,
                wind_deg: 158,
                wind_gust: 9.07,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711645200,
                temp: 2.38,
                feels_like: -0.72,
                pressure: 1015,
                humidity: 87,
                dew_point: 0.32,
                uvi: 0,
                clouds: 70,
                visibility: 10000,
                wind_speed: 3.1,
                wind_deg: 150,
                wind_gust: 9.29,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711648800,
                temp: 2.07,
                feels_like: -1.27,
                pressure: 1015,
                humidity: 88,
                dew_point: 0.16,
                uvi: 0,
                clouds: 75,
                visibility: 10000,
                wind_speed: 3.32,
                wind_deg: 151,
                wind_gust: 10.89,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1711652400,
                temp: 1.68,
                feels_like: -1.66,
                pressure: 1014,
                humidity: 89,
                dew_point: 0.02,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 3.22,
                wind_deg: 155,
                wind_gust: 11.15,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
        ],
        daily: [
            {
                dt: 1711443600,
                sunrise: 1711422923,
                sunset: 1711468482,
                moonrise: 1711474080,
                moonset: 1711423980,
                moon_phase: 0.53,
                temp: {
                    day: 1.29,
                    min: -0.25,
                    max: 3.22,
                    night: 3.22,
                    eve: 0.68,
                    morn: -0.22,
                },
                feels_like: {
                    day: -1.02,
                    night: 1.05,
                    eve: -2.34,
                    morn: -2.12,
                },
                pressure: 1013,
                humidity: 100,
                dew_point: 1.29,
                wind_speed: 2.62,
                wind_deg: 13,
                wind_gust: 6.98,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 100,
                pop: 0,
                uvi: 2.03,
            },
            {
                dt: 1711530000,
                sunrise: 1711509165,
                sunset: 1711555002,
                moonrise: 1711565220,
                moonset: 1711510680,
                moon_phase: 0.56,
                temp: {
                    day: 0.81,
                    min: -2.84,
                    max: 2.68,
                    night: -1.17,
                    eve: 0.74,
                    morn: -2.84,
                },
                feels_like: {
                    day: -2.02,
                    night: -1.17,
                    eve: 0.74,
                    morn: -6.66,
                },
                pressure: 1017,
                humidity: 97,
                dew_point: 0.19,
                wind_speed: 2.99,
                wind_deg: 352,
                wind_gust: 5.6,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 99,
                pop: 0,
                uvi: 2.33,
            },
            {
                dt: 1711616400,
                sunrise: 1711595407,
                sunset: 1711641522,
                moonrise: 1711656600,
                moonset: 1711597500,
                moon_phase: 0.59,
                temp: {
                    day: 3.49,
                    min: -1.85,
                    max: 5.41,
                    night: 1.44,
                    eve: 3.83,
                    morn: -1.85,
                },
                feels_like: {
                    day: 0.59,
                    night: -1.99,
                    eve: 0.91,
                    morn: -3.98,
                },
                pressure: 1019,
                humidity: 81,
                dew_point: 0.41,
                wind_speed: 3.93,
                wind_deg: 174,
                wind_gust: 11.78,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 96,
                pop: 0,
                uvi: 2.45,
            },
            {
                dt: 1711702800,
                sunrise: 1711681650,
                sunset: 1711728042,
                moonrise: 0,
                moonset: 1711684500,
                moon_phase: 0.63,
                temp: {
                    day: 5.47,
                    min: 1.41,
                    max: 6.03,
                    night: 4.84,
                    eve: 4.71,
                    morn: 2.12,
                },
                feels_like: {
                    day: 2.79,
                    night: 1.9,
                    eve: 2.32,
                    morn: -0.84,
                },
                pressure: 1007,
                humidity: 84,
                dew_point: 3.01,
                wind_speed: 4.16,
                wind_deg: 153,
                wind_gust: 11.68,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 100,
                pop: 0,
                uvi: 1.37,
            },
            {
                dt: 1711789200,
                sunrise: 1711767892,
                sunset: 1711814562,
                moonrise: 1711748100,
                moonset: 1711771800,
                moon_phase: 0.66,
                temp: {
                    day: 9.34,
                    min: 3.99,
                    max: 11.42,
                    night: 9.5,
                    eve: 11.42,
                    morn: 3.99,
                },
                feels_like: {
                    day: 6.78,
                    night: 6.75,
                    eve: 10.16,
                    morn: 0.81,
                },
                pressure: 1014,
                humidity: 64,
                dew_point: 2.93,
                wind_speed: 5.57,
                wind_deg: 224,
                wind_gust: 14.3,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                clouds: 62,
                pop: 0,
                uvi: 2.28,
            },
            {
                dt: 1711875600,
                sunrise: 1711854135,
                sunset: 1711901082,
                moonrise: 1711839540,
                moonset: 1711859700,
                moon_phase: 0.69,
                temp: {
                    day: 12.08,
                    min: 6.49,
                    max: 14.59,
                    night: 9.48,
                    eve: 13.01,
                    morn: 6.49,
                },
                feels_like: {
                    day: 10.81,
                    night: 9.48,
                    eve: 11.7,
                    morn: 3.67,
                },
                pressure: 1015,
                humidity: 56,
                dew_point: 3.57,
                wind_speed: 5.88,
                wind_deg: 234,
                wind_gust: 15.06,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                clouds: 70,
                pop: 0,
                uvi: 2.99,
            },
            {
                dt: 1711962000,
                sunrise: 1711940378,
                sunset: 1711987602,
                moonrise: 1711930380,
                moonset: 1711948680,
                moon_phase: 0.72,
                temp: {
                    day: 15.07,
                    min: 6.16,
                    max: 16.54,
                    night: 11.75,
                    eve: 14.5,
                    morn: 6.16,
                },
                feels_like: {
                    day: 14.15,
                    night: 10.94,
                    eve: 13.52,
                    morn: 4.37,
                },
                pressure: 1014,
                humidity: 58,
                dew_point: 6.89,
                wind_speed: 5.33,
                wind_deg: 192,
                wind_gust: 12.26,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 85,
                pop: 0,
                uvi: 3,
            },
            {
                dt: 1712048400,
                sunrise: 1712026621,
                sunset: 1712074122,
                moonrise: 1712020080,
                moonset: 1712039100,
                moon_phase: 0.75,
                temp: {
                    day: 13.99,
                    min: 7.99,
                    max: 16.28,
                    night: 13.14,
                    eve: 14.61,
                    morn: 7.99,
                },
                feels_like: {
                    day: 13.04,
                    night: 12.21,
                    eve: 13.67,
                    morn: 5.4,
                },
                pressure: 1004,
                humidity: 61,
                dew_point: 6.54,
                wind_speed: 6.64,
                wind_deg: 193,
                wind_gust: 13.59,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                clouds: 100,
                pop: 0.2,
                rain: 0.15,
                uvi: 3,
            },
        ],
        alerts: [
            {
                sender_name: 'web@mecom.ru',
                event: 'Other dangers',
                start: 1711479600,
                end: 1711612800,
                description: '',
                tags: ['Other dangers'],
            },
            {
                sender_name: 'web@mecom.ru',
                event: 'Прочие опасности',
                start: 1711479600,
                end: 1711612800,
                description: 'В ночные и утренние часы на дорогах местами гололедица.',
                tags: ['Other dangers'],
            },
        ],
    };
};
